name: Build and Deploy Manually

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: |
          echo "API_URL_GITHUB=${{ secrets.API_URL_GITHUB }}" >> $GITHUB_ENV
          echo "API_TOKEN_GITHUB=${{ secrets.API_TOKEN_GITHUB }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
      
      - name: Debug API Token
        run: |
          echo "API_TOKEN_GITHUB is set: ${API_TOKEN_GITHUB}"

      - name: Lint the code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
        env:  # Pass secrets explicitly
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          API_URL_GITHUB: ${{ secrets.API_URL_GITHUB }}
          PORT: ${{ secrets.PORT }}
